spring:
  profiles:
    include:
      # get properties of domain project resources/application-domain.yml
      - domain

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    initialization-mode: always
    schema: classpath:schema.sql
    data: classpath:data.sql

server:
  port: 80
